name: Task2 CI

on:
  push:
    branches: [ "task2" ]
  pull_request:
    branches: [ "task2" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpng-dev clang-format

    - name: Build main executable
      run: make

    - name: Run property tests
      run: make test

    - name: Check code formatting
      run: make format-check